#server配置
#server:
  #port: 8010

#应用配置
spring:
  application:
    name: movie-consumer-feign
# 配置消息队列
  #rabbitmq:
    #host: 192.168.40.1
    #username: hdd
    #password: hdd
    #port: 5672 # rabbitmq的默认端口时5672

#eureka client配置
eureka:
  client:
    service-url:
     #defaultZone: http://localhost:8761/eureka 
     defaultZone: http://${eurekaserver.anthen.user}:${eurekaserver.anthen.password}@eurekaserver:8761/eureka 
     #defaultZone: http://${eurekaserver.anthen.user}:${eurekaserver.anthen.password}@eurekaserver:8761/eureka, http://${eurekaserver.anthen.user}:${eurekaserver.anthen.password}@eurekaserverha:8762/eureka 
  instance:
    prefer-ip-address: true

# 为feign启用hystrix
feign:
  hystrix:
    enabled: true

#自定义的属性
eurekaserver:
  anthen:
    user: mycloud
    password: 123


# 配置ribbon
user-provider:
 ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略

env: dev1231111@@refresh
ppp: test-123

